version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    nodejs: "18"
  apt_packages:
    - graphviz
    - npm
  jobs:
    post_build:
      - echo "Command run at 'post_build' step"
      - echo `date`
      - echo "$READTHEDOCS_OUTPUT/html"
      - node --version
      - npm install
      - npm run build:examples
      - pwd
      - ls
      - cp -r docs/build/html/examples "$READTHEDOCS_OUTPUT/html"