version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    nodejs: "18"
  apt_packages:
    - graphviz
    - npm

  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - uv venv
    install:
      - uv pip install -r requirements.txt
    build:
       html:
         - uv run sphinx-build -T -b html docs $READTHEDOCS_OUTPUT/html

sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/source/conf.py
