version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    nodejs: "18"
  apt_packages:
    - graphviz
    - npm

  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv venv
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv tree
    # install:
    #   - uv pip install -r docs/requirements.txt
    build:
       html:
         - echo $READTHEDOCS_OUTPUT
         - mkdir -p $READTHEDOCS_OUTPUT/html/         
         - ls docs/source
         - ls $READTHEDOCS_OUTPUT
         - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv run sphinx-build --version
         - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv run sphinx-build -v -T -b html -c docs/source/ docs/source $READTHEDOCS_OUTPUT/html
