version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    nodejs: "18"
  apt_packages:
    - graphviz
    - npm
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv venv $READTHEDOCS_VIRTUALENV_PATH
    - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv --preview pip install .[docs,pandas,flask,fastapi,rdflib]
    - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv --preview pip install docs/requirements.txt
  build:
    html:
      - uv run sphinx-build -T -b html docs $READTHEDOCS_OUTPUT/html

# python:
#    install:
#      - requirements: docs/requirements.txt

sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/source/conf.py
