import { Segment } from './SmartRowCache';
import { DFData } from './DFWhole';
export declare const segA: Segment;
export declare const dataA: DFData;
export declare const segB: Segment;
export declare const dataB: DFData;
export declare const segBShort: Segment;
export declare const dataBShort: DFData;
export declare const segC: Segment;
export declare const dataC: DFData;
export declare const segD: Segment;
export declare const dataD: DFData;
export declare const segE: Segment;
export declare const dataE: DFData;
export declare const segBD: Segment;
export declare const dataBD: DFData;
export declare const segBE: Segment;
export declare const dataBE: DFData;
export declare const segAOffset: Segment;
export declare const segBOffset: Segment;
export declare const segCOffset: Segment;
export declare const fullData09: DFData;
export declare const fullData015: DFData;
