name: 'ðŸž Bug report - Python'
description: Report an issue with Buckaroo.
labels: [bug, python]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: >
            I have checked that this issue has not already been reported.
          required: true
        - label: >
            I have confirmed this bug exists on the
            [latest version](https://github.com/paddymul/buckaroo) of Polars.
          required: true

  - type: dropdown
    id: Notebook-system
    attributes:
      label: What type of jupyter notebook were you using (VSCode notebook, google colab, Jupyter Lab, Jupyter notebook).  Select multiple if you can reproduce this in multiple environments.  If other, please add to description.
      multiple: true
      options:
        - VS Code
        - Jupyter Lab
        - Google Colab
        - Jupyter Notebook
        - Other
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Reproducible example
      description: >
        Please follow [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) on how to
        provide a minimal, copy-pastable example. Include the (wrong) output if applicable.  If this is a visual bug, provide a screenshot of the input dataframe and the top couple of lines of buckaroo output.
      value: |
        ```python

        ```
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Jupyter Log output
      description: >
        If the buckaroo widget completely didn't display, check the Jupyter Log Console.  Also check the javascript console of the browser to see if any obvious JS errors occurred.  This is optional
        Paste the output of the logs  here.
      render: shell

  - type: textarea
    id: problem
    attributes:
      label: Issue description
      description: >
        Provide any additional information you think might be relevant.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: >
        Describe or show a code example of the expected behavior.
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Installed versions
      description: >
        Paste the output of ``buckaroo.debug_packages()``
      value: |
        <details>

        ```
        Replace this line with the output of pl.show_versions(). Leave the backticks in place.
        ```

        </details>
    validations:
      required: true

