version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    nodejs: "18"
  apt_packages:
    - graphviz
    - npm
  jobs:
    pre_create_environment:
      - asdf plugin add uv
      - asdf plugin add pnpm
      - asdf install pnpm 9.5.0
      - asdf global pnpm 9.5.0
      - asdf install uv 0.6.12
      - asdf global uv 0.6.12
    create_environment:
      - uv venv
#     - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --all-extras --group docs
    install:
      - uv sync  --all-extras --group dev
      - uv tree
      - pnpm -C packages/buckaroo-js-core install
    build:
      html:
        - uv tree
        - uv venv
        - uv run sphinx-build -T -b html docs/source  $READTHEDOCS_OUTPUT/html
        - ./scripts/marimo_wasm_output.sh buckaroo_ddd_tour.py run
        - ./scripts/marimo_wasm_output.sh buckaroo_compare.py edit
        - ./scripts/marimo_wasm_output.sh full_tour.py edit
        - pnpm -C packages/buckaroo-js-core run build-storybook
        - cp -r packages/buckaroo-js-core/dist/storybook docs/extra-html/
        - cp -r docs/extra-html/* $READTHEDOCS_OUTPUT/html

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/source/conf.py
   
 
